# Generated by Django 5.1.4 on 2024-12-16 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Brand Image')),
            ],
        ),
        migrations.CreateModel(
            name='CaseShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_shape', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GlassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_feature', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='ProductImage')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.brand')),
                ('case_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.caseshape')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.gender')),
                ('glass_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.glassfeature')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.mechanisim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strap_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.straptype')),
                ('tarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.style')),
            ],
        ),
    ]
