# Generated by Django 5.1.4 on 2024-12-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseShape',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='GlassFeature',
            new_name='Gemstone',
        ),
        migrations.RenameModel(
            old_name='StrapType',
            new_name='Material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mechanism',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='case_shape',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gemstone',
            old_name='glass_feature',
            new_name='gemstone',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='strap_type',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='case_shape',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='strap_type',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tarz',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glass_feature',
        ),
        migrations.AddField(
            model_name='product',
            name='gemstone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppEcommerce.gemstone'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Mechanisim',
        ),
    ]
