# Generated by Django 5.1.4 on 2024-12-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0002_rename_caseshape_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='gemstone_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='gemstone_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='gender_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_tr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='style_tr',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
